### ISSUE TITLE
Invalidate cached Docker image

### ISSUE THREAD

**Issue by BNAndras** [exercism/pyret-test-runner#18]
I was hoping #16 would invalidate the cached test runner image, but I'm seeing `Could not find builtin module math in any of /mnt/exercism-iteration/.pyret/compiled, /usr/local/lib/node_modules/pyret-npm/pyret-lang/build/phaseA/lib-compiled` which is solved in pyret-npm v0.27. Can you work your magic and get the Docker image to be rebuilt?

**Comment by ErikSchierboom** [comment]
#16 only updates the tests, which are not part of the Dockerfile and thus do not invalidate it. Even if they did, the installation of the `pyret-npm` package is done before those files would have nbeen copied, so it wouldn't affect the installation of the package. 

> Can you work your magic and get the Docker image to be rebuilt?

I actually can't do anything more than what you do, but I do have an easy fix: install a specific version of the node package in the Dockerfile. So in https://github.com/exercism/pyret-test-runner/blob/main/Dockerfile#L5, you have this line:

```
npm install -g pyret-npm
```

Change that to:

```
npm install -g pyret-npm@0.0.27
```

That way, you can control exactly what version is being used _and_ updating it in the future will cause the image to be rebuilt.

Side note: you can also use `ARG` to define the version somewhere at the beginning of the Dockerfile, something like:

```dockerfile
FROM alpine:3.17
ARG PYRET_NPM_VERSION=0.0.27

# install packages required to run the tests
RUN apk add --no-cache jq coreutils nodejs npm && \
    npm install -g pyret-npm@$PYRET_NPM_VERSION
```

See https://docs.docker.com/engine/reference/builder/#arg
